name: Cypress_run

on: push

env:
  FORCE_COLOR: 1

jobs:
  Headless:
    name: Cypress_run
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cypress install
        run: |
          npm install cypress
      - name: Cypress Report
        uses: cypress-io/github-actions@v2
        with:
          build: npm run build
          start: npm start
          record: true
        env: 
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}  
      
  nodechecker:
    name: node_modules checker
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Check node_modules existence
        run: |
          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set up a .gitignore file with this folder included on it to prevent this from happening in the future." && exit 1; fi